spin_manifest_version = 2

[application]
name = "image-classification"
version = "0.1.0"
authors = ["Radu Matei <radu@fermyon.com>"]

[[trigger.http]]
route = "/api/..."
component = "api"

[[trigger.http]]
route = "/..."
component = "frontend"


[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "frontend", destination = "/" }]

[component.api]
source = "api/target/tsapi.wasm"
allowed_outbound_hosts = []

[component.api.dependencies]
"component:image-classification-lib/image-classification" = { version = "^0.0.3", registry = "fermyon.com", package = "fermyon-experimental:image-classification-lib" }
# "component:image-classification-lib/image-classification" = { path = "lib/target/wasm32-wasip1/release/image_classification_lib.wasm" }

[component.api.build]
command = "npm run build"
workdir = "api"
